In [ ]:
#AISHWARYA GANDHI.M
#AMB2011

In [ ]:
import pandas as pd
production=pd.Series(
    [30,60,45,25],
    index=["Wheat","Rice","Maize","Barley"]
)
print(production)

Wheat     30
Rice      60
Maize     45
Barley    25
dtype: int64

In [ ]:
#loc=location by label or value
print(production.loc["Rice"])

print(production.loc["Wheat"])

60
30

In [ ]:
#iloc= location by index
print(production.iloc[0])

30

In [ ]:
print(production.sum())
print(production.mean())
print(production.max())#Maximum production crop
print(production.idxmax())   #it print the index label of the maximum value in the series

print(production.idxmax(),"is having maximum value of ", production.max())

160
40.0
60
Rice
Rice is having maximum value of  60

In [ ]:
#increased all crop production by 10%(good harvest year)
increased_production=production*1.10
print(increased_production)

Wheat     33.0
Rice      66.0
Maize     49.5
Barley    27.5
dtype: float64

In [ ]:
#Crop with production grater than 40 tons
high_production=production[production>40]
print(high_production)
print()

print(production>40)

Rice     60
Maize    45
dtype: int64

Wheat     False
Rice       True
Maize      True
Barley    False
dtype: bool

In [ ]:
import pandas as pd

df=pd.DataFrame({
    "name":["Akhil","Bobby","Charan"],
    "age":[25,30,35],
    "city":["NY","LA","Chicago"]
},index=["a","b","c"])

print(df)
print()
print(df.loc["b"])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

name    Bobby
age        30
city       LA
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

     name     city
a   Akhil       NY
c  Charan  Chicago

In [ ]:
print(df.loc["a":"c"])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

In [ ]:



print(df.loc[df["age"] > 28, ["name", "age"]])

     name  age
b   Bobby   30
c  Charan   35

In [ ]:
print(df.iloc[[0,2],[0,2]])

     name     city
a   Akhil       NY
c  Charan  Chicago

In [ ]:
print(df.iloc[0:2])
#0 is rows
#2 is column

    name  age city
a  Akhil   25   NY
b  Bobby   30   LA

In [ ]:
df["name"]

a     Akhil
b     Bobby
c    Charan
Name: name, dtype: object

In [ ]:
df[["name", "age"]]

     name  age
a   Akhil   25
b   Bobby   30
c  Charan   35

In [ ]:
import pandas as pd
data={
    "Farm":["Farm A","Farm B","Farm C","Farm D"],
    "Crop":["Wheat","Rice","Wheat","Maize"],
    "Area_hectares":[10,15,8,12],
    "Production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [ ]:
df.head()

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [ ]:
df.tail()

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [ ]:
df.head(2)#give from starting

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60

In [ ]:
df.tail(2)#give from ending

     Farm   Crop  Area_hectares  Production_tons
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [ ]:
df.describe()

       Area_hectares  Production_tons
count       4.000000         4.000000
mean       11.250000        37.500000
std         2.986079        15.779734
min         8.000000        24.000000
25%         9.500000        28.500000
50%        11.000000        33.000000
75%        12.750000        42.000000
max        15.000000        60.000000

In [ ]:
#yield=production/area
df["Yield_tons_per_hectare"]=df["Production_tons"]/df["Area_hectares"]
print(df)

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
0  Farm A  Wheat             10               30                     3.0
1  Farm B   Rice             15               60                     4.0
2  Farm C  Wheat              8               24                     3.0
3  Farm D  Maize             12               36                     3.0

In [ ]:
print(df.iloc[0:2])

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
0  Farm A  Wheat             10               30                     3.0
1  Farm B   Rice             15               60                     4.0

In [ ]:
print(df.iloc[1:4])

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
1  Farm B   Rice             15               60                     4.0
2  Farm C  Wheat              8               24                     3.0
3  Farm D  Maize             12               36                     3.0

In [ ]:
print(df.iloc[[1,3]])

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
1  Farm B   Rice             15               60                     4.0
3  Farm D  Maize             12               36                     3.0

In [ ]:
df.iloc[[1,3],[0,3]]

     Farm  Production_tons
1  Farm B               60
3  Farm D               36

In [ ]:
df.iloc[[1,3],[0,1,2]]

     Farm   Crop  Area_hectares
1  Farm B   Rice             15
3  Farm D  Maize             12

In [ ]:
df.loc[[1,3], ['Farm','Crop','Area_hectares']]

     Farm   Crop  Area_hectares
1  Farm B   Rice             15
3  Farm D  Maize             12

In [ ]:
#Filter data
#Farms growing wheat
print(df[df["Crop"]=="Wheat"])
print()
wheat_farms=df[df["Crop"]=="Wheat"]
print(wheat_farms)

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
0  Farm A  Wheat             10               30                     3.0
2  Farm C  Wheat              8               24                     3.0

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
0  Farm A  Wheat             10               30                     3.0
2  Farm C  Wheat              8               24                     3.0

In [ ]:
#farm with yeild greater than 3
high_yield=df[df["Yield_tons_per_hectare"]>3]
print(high_yield)

     Farm  Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
1  Farm B  Rice             15               60                     4.0

In [ ]:
#sort the farms by highest production
sorted_df=df.sort_values(by="Production_tons",ascending=False)
print(sorted_df)

     Farm   Crop  Area_hectares  Production_tons  Yield_tons_per_hectare
1  Farm B   Rice             15               60                     4.0
3  Farm D  Maize             12               36                     3.0
0  Farm A  Wheat             10               30                     3.0
2  Farm C  Wheat              8               24                     3.0

In [ ]:
#Group By operation -Average yeild per crop
avg_yield=df.groupby("Crop")["Yield_tons_per_hectare"].sum()
print(avg_yield	)

Crop
Maize    3.0
Rice     4.0
Wheat    6.0
Name: Yield_tons_per_hectare, dtype: float64